### ISSUE TITLE
Error in upload: Broken Pipe

### ISSUE THREAD

**Issue by irtimood** [woxxy/MySQL-backup-to-Amazon-S3#14]
I configured all and i think it's all fine but i got an error when the system try to upload to s3:

WARNING: Upload failed: /day/mysqldbBackup.12.18.2013.tar.gz ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.25)

I got this error several time until i got:

ERROR: Upload of '/root/mysqldbBackup.12.18.2013.tar.gz' failed too many times. Skipping that file.

Do i have to change something on bucket configuration?

Thanks in advantage,

Dimitri

**Comment by jgc94131** [comment]
Look at the settings file. What worked for me was increasing the write size to 8k.

**Comment by irtimood** [comment]
Thanks, solved :)
