### ISSUE TITLE
multiple database

### ISSUE THREAD

**Issue by iamkingsleyf** [woxxy/MySQL-backup-to-Amazon-S3#19]
Hello;

How can i use this to upload multiple DB on a server?

**Comment by codex73** [comment]
What do you mean @iamkingsleyf "upload multiple DB on a server"? The script is designed to grab a dump of your configured settings database server and upload to Amazon S3.

**Comment by mgntrn** [comment]
I think he means that a sql-dump is created for each database, instead of one combined sql file.

**Comment by iamkingsleyf** [comment]
i now understand how it works, with the help of automysqlbackup i use it to backup multiple DBs
